config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions"
    # unlocks: "users/unlocks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    resources :users, only: %i[index show] do
      member do
        get :stocked
        get :mentor
        get :edit_avatar
      end
      resources :notifications, only: %i[index update] do
        collection do
          patch :read_all
          delete :destroy_all
        end
      end
      resources :chat_rooms, only: %i[index show create] do
        collection do
          get :user_index
        end
      end
    end
  end

  resources :users_csv, only: %i[create index]

  resources :issues do
    resources :favorites, only: %i[create destroy]
    resources :stocks, only: %i[create destroy]
    resources :comments, only: %i[create edit update destroy]
  end
  resources :groupings, only: %i[create destroy]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  include SqlHelper
  extend ActionTextValidate

  before_create :notify

  belongs_to :user
  belongs_to :issue
  has_rich_text :content
  has_one :_content, class_name: "ActionText::RichText", as: :record
  has_one :notification, as: :subject, dependent: :destroy

  validates :content, presence: true
  validate :validate_content_attachment_byte_size

  MAX_MEGA_BYTES = 5
  create_validate_attachment :content, MAX_MEGA_BYTES

  # 通知を生成するメソッド(メソッド名共通)
  def notify
    return if user == issue.user
    build_notification do |note|
      note.user = issue.user
      note.message = Comment.human_attribute_name(:notify_message, issue: issue.title, user: user.name)
      note.link_path = Rails.application.routes.url_helpers.issue_path(issue)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: %i[create edit update destroy]
  before_action :set_comments, only: %i[create edit update destroy]
  before_action :set_comment, only: %i[edit update destroy]
  before_action :set_comments, only: %i[create edit update destroy]
  before_action :author_required, only: %i[edit update destroy]

  def create
    @comment = current_user.comments.build(comment_params.merge(issue_id: @issue.id))
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @issue }
        format.js { render :index }
      else
        format.html { render "issues/show" }
        format.js { render :error }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js { render :edit }
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render :after_update }
      else
        format.html { render "issues/show" }
        format.js { render :error }
      end
    end
  end

  def destroy
    respond_to do |format|
      @comment.destroy
      format.js { render :after_update }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :issue_id)
  end

  def set_issue
    @issue = Issue.find(params[:issue_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_comments
    set_issue
    @comments = @issue.comments.includes(:user).with_rich_text_content.past
  end

  def author_required
    set_comment
    unless current_user == @comment.user
      flash[:danger] = I18n.t("views.comments.flash.author_required")
      redirect_back fallback_location: issues_path
    end
  end
end

app/views/comments/_comment.html.erb
<div class="default-container" id=<%= "this-comment-#{comment.id}" %>>
  <div class="issue-abst-header">
    <div class="issue-author-profile">
      <%= image_tag prepare_avatar(comment.user), class: "avatar50" %>
      <%= content_tag(:span, comment.user.code, class: "right-p5") %>
      <%= content_tag(:span, comment.user.name, class:"right-p5 issue-item-user") %>
      <%= content_tag(:span, time_ago_in_words(comment.created_at)) %>
      <% if edited?(comment) %>
        <%= content_tag(:span, t("views.edited"), class: "edited") %>
      <% end %>
    </div>
  </div>
  <div class="comment-content-container">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <div class="comment-btn-container">
      <%= link_to edit_issue_comment_path(issue, comment), class:"comment-edit-btn", remote: true do %>
        <span class="material-icons">edit_note</span>
      <% end %>
      <%= link_to issue_comment_path(issue, comment), class: "comment-delete-btn", remote: true, method: :delete, data: {confirm: t("views.comments.confirm.delete")} do %>
        <span class="material-icons">delete_forever</span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/_error_message.html.erb
<% if comment.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= t("errors.messages.title", count: comment.errors.size) %></h4>
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <%= content_tag(:li, message) %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="comment-container" id=<%= "comment-form-#{comment.id}" %>>
  <%= form_with(model: [issue, comment],class: "form", remote: true) do |form| %>
    <div id=<%= "error-explanation-#{comment.id}" %>>
      <%= render "comments/error_message", comment: comment %>
    </div>

    <div class="form-group">
      <%= form.label :content, class: "sr-only" %>
      <%= form.rich_text_area :content, require: true, placeholder: Comment.human_attribute_name(:content) %>
    </div>
    <div class="btn2-container">
      <%= form.submit class: "btn btn-primary", id: "comment-btn-#{comment.id}" %>
      <%= link_to t("views.btn.top"), "#issue-top", class: "btn btn-warning btn-block" %>
    </div>
  <% end %>
</div>

app/views/comments/after_update.js.erb
$("#comments-area").html("<%= j(render @comments, issue: @issue) %>");

app/views/comments/edit.js.erb
$("#this-comment-<%= @comment.id %>").replaceWith("<%= j(render 'form', comment: @comment, issue: @issue) %>")

app/views/comments/error.js.erb
$("#error-explanation-<%= @comment.id %>").html("<%= j(render 'error_message', comment: @comment)%>");
$("html,body").animate({scrollTop:$("#comment-form-<%= @comment.id%>").offset().top});

app/views/comments/index.js.erb
$("#error-explanation-").html("<%= j(render 'error_message', comment: @comment)%>");
$("#comments-area").html("<%= j(render @comments, issue: @issue) %>");
$("trix-editor.trix-content").val("");
$("html,body").animate({scrollTop:$("#comment-form-").offset().top});