config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions"
    # unlocks: "users/unlocks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    resources :users, only: %i[index show] do
      member do
        get :stocked
        get :mentor
        get :edit_avatar
      end
      resources :notifications, only: %i[index update] do
        collection do
          patch :read_all
          delete :destroy_all
        end
      end
      resources :chat_rooms, only: %i[index show create] do
        collection do
          get :user_index
        end
      end
    end
  end

  resources :users_csv, only: %i[create index]

  resources :issues do
    resources :favorites, only: %i[create destroy]
    resources :stocks, only: %i[create destroy]
    resources :comments, only: %i[create edit update destroy]
  end
  resources :groupings, only: %i[create destroy]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/notification.rb
class Notification < ApplicationRecord
  include SqlHelper

  belongs_to :subject, polymorphic: true
  belongs_to :user

  validates :message, presence: true
  validates :link_path, presence: true

  scope :unreads, -> { where(read: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: :index

  def index
    @user = User.find(params[:user_id])
    @notifications = @user.notifications.recent.page(params[:page])
  end

  def update
    @notification = Notification.find(params[:id])
    @notification.toggle!(:read) unless @notification.read?
    redirect_to @notification.link_path
  end

  def read_all
    user = User.find(params[:user_id])
    @notifications = user.notifications
    @notifications.unreads.each{ _1.toggle!(:read) }
    redirect_to user_notifications_path(user)
  end

  def destroy_all
    user = User.find(params[:user_id])
    @notifications = user.notifications
    if @notifications.present?
      @notifications.destroy_all
      flash[:danger] = I18n.t("views.notifications.flash.delete_all")
    end
    redirect_to user_notifications_path(user)
  end

  private

  def ensure_correct_user
    user = User.find(params[:user_id])
    redirect_back fallback_location: root_path unless current_user == user
  end
end

app/views/notifications/_notification.html.erb
<%= link_to user_notification_path(user, notification), method: :patch, class:"notification-link", id: "notification-link-#{notification.id}" do %>
  <%= content_tag(:div, class: "default-container #{unread_css(notification)}", id: "this-notification-#{notification.id}") do %>
      <%= simple_format notification.message %>
      <span><%= time_ago_in_words notification.created_at %></span>
  <% end %>
<% end %>

app/views/notifications/index.html.erb
<% provide(:title, t("views.notifications.index.title")) %>

<h1><%= t("views.notifications.index.title") %></h1>
<div id="unread-count">
  <span class="pink-line"><%= "#{Notification.human_attribute_name(:unread)}: #{@user.notifications.unreads.size}" %></span>
</div>
<div class="remark">
  <p><%= t("views.notifications.index.remark01") %></p>
</div>
<div class="btn2-container">
  <%= link_to t("views.notifications.index.read_all"), read_all_user_notifications_path, method: :patch, class: "btn btn-warning read-all" %>
  <%= link_to t("views.notifications.index.delete_all"), destroy_all_user_notifications_path, method: :delete, class: "btn btn-danger destroy-all", data: {confirm: t("views.notifications.confirm.delete_all")} %>
</div>

<%= render @notifications, user: @user %>
<% if @notifications.blank? %>
  <h4 class="blank-danger"><%= t("views.blank") %></h4>
<% end %>
<%= paginate @notifications %>

<%= javascript_pack_tag 'notify' %>