config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions"
    # unlocks: "users/unlocks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    resources :users, only: %i[index show] do
      member do
        get :stocked
        get :mentor
        get :edit_avatar
      end
      resources :notifications, only: %i[index update] do
        collection do
          patch :read_all
          delete :destroy_all
        end
      end
      resources :chat_rooms, only: %i[index show create] do
        collection do
          get :user_index
        end
      end
    end
  end

  resources :users_csv, only: %i[create index]

  resources :issues do
    resources :favorites, only: %i[create destroy]
    resources :stocks, only: %i[create destroy]
    resources :comments, only: %i[create edit update destroy]
  end
  resources :groupings, only: %i[create destroy]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :avatar
  has_one :group, dependent: :destroy
  has_many :groupings, dependent: :destroy
  has_many :join_groups, through: :groupings, source: :group
  has_many :issues, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_issues, through: :favorites, source: :issue
  has_many :stocks, dependent: :destroy
  has_many :stock_issues, through: :stocks, source: :issue
  has_many :comments, dependent: :destroy
  has_many :comment_issues, through: :comments, source: :issue
  has_many :notifications, dependent: :destroy
  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users, source: :chat_room
  has_many :messages, dependent: :destroy
  acts_as_tagger

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  before_validation :code_to_6
  before_create :make_the_first_user_admin
  before_update :prevent_change_admin!
  before_destroy :prevent_destroy_admin!
  after_save_commit :group_create_or_destroy_depend_on_mentor

  validates :name, presence: true, length: {maximum: 255}
  validates :code, presence: true, length: {is: 6}, uniqueness: true
  attribute :mentor, :boolean, default: false
  validates :entered_at, presence: true
  attribute :admin, :boolean, default: false
  validate :validate_avatar_attachment_byte_size

  MAX_MEGA_BYTES = 2
  MAX_AVATAR_ATTACHMENT_BYTE_SIZE = MAX_MEGA_BYTES * (1_024 ** 2)

  def self.guest_admin_user
    find_or_create_by!(code: "_admin") do |user|
      user.name = "ゲスト管理者"
      user.email = "guest_admin@diver.com"
      user.entered_at = Date.new(2014, 4, 1)
      user.password = "password"
      user.mentor = true
      user.admin = true
    end
  end

  def self.guest_user
    find_or_create_by!(code: "_guest") do |user|
      user.name = "ゲスト"
      user.email = "guest@diver.com"
      user.entered_at = Date.new(Date.current.year, 4, 1)
      user.password = "password"
    end
  end

  def self.csv_columns
    { "No" => :id,
      "職員コード(6桁)" => :code,
      "名前" => :name,
      "Eメール" => :email,
      "パスワード(6文字以上)" => :password,
      "入職日(例:2000-04-01)" => :entered_at }
  end

  def group_member_issues
    return unless mentor?
    Issue.where(user_id: group.members&.pluck(:id))
  end

  def guest?
    [User.guest_user, User.guest_admin_user].include?(self)
  end

  scope :order_by_code, -> { order(:code) }

  private

  def prevent_change_admin!
    return unless admin_change == [true, false] && User.where(admin: true).size == 1
    errors.add(:base, I18n.t("activerecord.errors.messages.prevent_loss_of_admin"))
    raise ActiveRecord::Rollback
  end

  def prevent_destroy_admin!
    return unless admin? && User.where(admin: true).size == 1
    errors.add(:base, I18n.t("activerecord.errors.messages.prevent_loss_of_admin"))
    raise ActiveRecord::Rollback
  end

  def non_guest_user_is_empty?
    User.where("(code != ?) AND (code != ?)", "_admin", "_guest").blank? && %w[_admin _guest].exclude?(code)
  end

  def make_the_first_user_admin
    self.attributes = {mentor: true, admin: true} if non_guest_user_is_empty?
    self
  end

  def group_create_or_destroy_depend_on_mentor
    return group&.destroy unless mentor
    create_group! if group.nil?
  end

  def validate_avatar_attachment_byte_size
    if (attachment = avatar.attachment) && attachment.byte_size > MAX_AVATAR_ATTACHMENT_BYTE_SIZE
      errors.add(
        :base,
        :avatar_attachment_byte_size_is_too_large,
        max_avatar_attachment_mega_byte_size: MAX_MEGA_BYTES,
        bytes: attachment.byte_size,
        max_bytes: MAX_AVATAR_ATTACHMENT_BYTE_SIZE
      )
    end
  end

  def code_to_6
    self.code = code.to_s.rjust(6, "0") if code.present?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!, only: %i[edit update destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    if params[:mentor]
      @user = User.find(params[:user_id])
      respond_to do |format|
        @user.toggle!(:mentor)
        format.html {redirect_to users_path}
        format.js {render "users/role_change"}
      end
    elsif params[:avatar]
      @user = User.find(params[:user_id])
      if @user.update(avatar: params.dig(:user, :avatar))
        redirect_to edit_user_registration_path(@user)
      else
        render "users/edit_avatar"
      end
    else
      super
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    resource
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    resource
  end

  def after_update_path_for(resource)
    resource
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_sign_in
    user = params[:admin] ? User.guest_admin_user : User.guest_user
    sign_in user
    flash[:success] = params[:admin] ? I18n.t("devise.sessions.guest_admin_signed_in") : I18n.t("devise.sessions.guest_signed_in")
    redirect_to user_path(user)
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    resource
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index show]
  before_action :ensure_correct_mentor, only: %i[index mentor]
  before_action :set_user, only: %i[show stocked mentor edit_avatar]
  before_action :ensure_correct_user, only: %i[show stocked]

  def index
    # 同じ変数をimportにも記載している。変更する場合は、importも変更すること
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).includes(:groupings).with_attached_avatar.order(:code).page(params[:page])
  end

  def show
    @q = @user.issues&.ransack(params[:q])
    @issues = @q.result(distinct: true).recent
  end

  def stocked
    @q = @user.stock_issues.includes(:stocks).ransack(params[:q])
    @issues = @q&.result(distinct: true)&.recent
  end

  def mentor
    @q = @user.group_member_issues&.ransack(params[:q])
    @issues = @q&.result(distinct: true)&.recent
    @group_member =
      if @user.group.members.pluck(:id).include?(params.dig(:q, :user_id_eq).to_i)
        User.find_by(id: params.dig(:q, :user_id_eq))
      end
  end

  def edit_avatar; end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_mentor
    redirect_back fallback_location: root_path unless current_user&.mentor
  end

  def ensure_correct_user
    set_user
    redirect_back fallback_location: root_path unless current_user == @user
  end
end

app/views/users/_member_profile.html.erb
<div class="card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs" id="group-members-nav">
      <% user.group.members.each do |member| %>
        <li class="nav-item">
          <% active = group_member == member ? "active" : nil %>
          <%= link_to member.name, redirect_to_current_path(anchor: nil, q: {user_id_eq: member.id}), class: "nav-link #{active}" %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="group-member-container">
    <% if group_member %>
      <span><%= "#{User.human_attribute_name(:entered_at)}: #{l(group_member.entered_at, format: :year)}" %></span>
      <% if (member_issues = group_member.issues.where.not(scope: :draft).presence) %>
        <h3 class="count-item">
          <%= link_to t("views.users.profile.pending_count"), redirect_to_current_path(q:{user_id_eq: group_member.id, status_eq: Issue.statuses[:pending] }) %>:
          <%= "#{member_issues.where(status: :pending).size} / #{member_issues.size}" %>
        </h3>
        <p>
          <% recent_issue = member_issues.recent.first %>
          <%= t "views.users.profile.recent_issue"%>(<%= time_ago_in_words recent_issue.created_at %>): <%= link_to recent_issue.title, issue_path(recent_issue) %>(<%= Issue.human_enum_status(recent_issue.status) %>)
        </p>
        <% member_issues.includes(:tags).tags_on(:tags).most_used(5).pluck(:name).each do |tag_name| %>
          <%= link_to tag_name, redirect_to_current_path(q:{user_id_eq: group_member.id, tags_name_eq: tag_name}), class: "tag lightgreen" %>
        <% end %>
      <% else %>
        <h4 class="blank-danger"><%= t("views.blank") %></h4>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_my_nav.html.erb
<nav class="nav nav-pills btn3-container">
  <%= link_to t("views.users.show.title"), user_path(user), class: "flex-fill text-center nav-link #{activate_css(:users, :show)}" %>
  <% if user.mentor? %>
    <%= link_to t("views.users.mentor.title"), mentor_user_path(user), class: "flex-fill text-center nav-link #{activate_css(:users, :mentor)}" %>
  <% end %>
  <%= link_to t("views.users.stocked.title"), stocked_user_path(user), class: "flex-fill text-center nav-link #{activate_css(:users, :stocked)}" %>
</nav>

app/views/users/_profile_format.erb
<div class="default-container profile-container">
  <div class="profile-avatar">
    <%= image_tag prepare_avatar(user), class: "avatar100" %>
  </div>
  <div class="profile-description">
    <div class="profile-name">
      <h2><%= user.name %></h2>
      <div class="user-edit-btn-container">
        <%= link_to t("views.btn.edit"), edit_user_registration_path, class: "user-edit-btn" %>
      </div>
    </div>
    <div class="grid-auto-150">
      <span><%= User.human_attribute_name(:code) %>: <%= user.code %></span>
      <span><%= User.human_attribute_name(:entered_at) %>: <%= l(user.entered_at, format: :year) %></span>
    </div>
    <div class="user-show-count grid-auto-150">
      <span class="count-item"><%= t("views.users.profile.issue_count")%>: <%= user.issues.size %></span>
      <span class="count-item"><%= t("views.users.profile.pending_count")%>: <%= user.issues.where(status: :pending).size %></span>
      <span class="count-item"><%= t("views.users.profile.favorite_count")%>: <%= Favorite.where(issue_id: user.issues.pluck(:id)).size %></span>
    </div>
    <% unless user.mentor %>
      <p>
        <%= User.human_attribute_name(:mentor) %>:
        <% user.join_groups&.each do |group| %>
          <span class="tag orange"><%= group.user.name %></span>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/_role_btn.html.erb
<%= button_to(user_registration_path(user_id: user.id, mentor: true), method: :put, class: "btn btn-outline-success", id: "btn-role-#{user.id}", remote: true, data: role_confirm(user)) do %>
  <% if user.mentor %>
    <%= t("views.users/role.mentor") %>
  <% else %>
    <%= t("views.users/role.non-mentor") %>
  <% end %>
<% end %>

app/views/users/_search.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link btn-block" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <%= t("views.btn.search") %>
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
          <%= search_form_for q, class: "form-inline" do |form| %>
            <div class="form-group">
              <%= form.label :name_or_code, class: "sr-only" %>
              <%= form.search_field :name_or_code_cont, class: "form-control", placeholder: t("views.ransack.name_or_code") %>
            </div>
            <div class="form-group">
              <%= form.label :mentor, class: "sr-only" %>
              <%= form.select :mentor_eq, {User.human_attribute_name(:mentor) => true, User.human_attribute_name(:staff) => false}, {include_blank: t("views.users.role")}, class: "form-control"  %>
            </div>
            <div class="form-group">
              <%= form.label :entered_at, class: "sr-only" %>
              <%= form.date_field :entered_at_eq, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.submit class: "btn btn-outline-primary btn-search" %>
            </div>
            <div class="form-group">
              <%= link_to t("views.btn.reset"), users_path, class: "btn btn-outline-danger" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_avatar.html.erb
<div class="login-form-container">
  <div class="login-form-sub-container">
    <div class="login-form-header">
      <h5 class="login-form-title"><%= t("views.users.edit_avatar.title") %></h5>
    </div>
    <%= form_with(model: @user, url: registration_path(@user, avatar: true, user_id: @user.id), class: "login-form", local: true) do |f| %>
      <%= render "devise/shared/error_messages", resource: @user %>
      <div class="avatar-container">
        <img src="#" alt="" id="avatar-prev" class="d-none avatar200">
        <%= image_tag prepare_avatar(@user), class: "avatar200", id: "avatar-img" %>
      </div>
      <%= content_tag(:small, t("views.users.edit_avatar.delete-avatar-caution"), class: "delete-avatar-caution attention") %>
      <div class="field">
        <%= f.label :avatar, class: "sr-only" %>
        <%= f.file_field :avatar, autocomplete: "avatar", class: "form-control", accept: "image/png, image/jpeg, image/jpg, image/gif, image/bmp" %>
      </div>
        <%= f.submit class: "btn btn-primary", data: {confirm: t("views.users.edit_avatar.confirm")} %>
    <% end %>
    <%= link_to t('devise.shared.links.back'), edit_user_registration_path, class: "btn btn-info btn-block" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t("views.users.index.title")) %>
<h1><%= t "views.users.index.title" %></h1>

<%= link_to t("views.users_csv.index.title"), users_csv_index_path, class: "btn btn-secondary btn-block" %>
<%= render "search", q: @q, users: @users %>

<div class="table-responsive-sm">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= Group.human_attribute_name(:members) %></th>
        <th><%= User.human_attribute_name(:avatar) %></th>
        <th><%= sort_link(@q, :name, class: "sort-link", id: "sort-user-name") %></th>
        <th><%= sort_link(@q, :code, class: "sort-link", id: "sort-user-code") %></th>
        <th><%= sort_link(@q, :mentor, t("views.users.role"), class: "sort-link", id: "sort-user-role") %></th>
        <th><%= User.human_attribute_name(:mentor) %></th>
        <th><%= User.human_attribute_name(:group_members) %></th>
        <th><%= sort_link(@q, :entered_at, class: "sort-link", id: "sort-user-entered_at") %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="middle">
            <div id=<%= "group-member-#{user.id}"%>><%= render "groupings/member_btn", user: user %></div>
          </td>
          <td><%= image_tag prepare_avatar(user), class: "avatar50" %></td>
          <td class="middle"><%= user.name %></td>
          <td class="middle"><%= user.code %></td>
          <td class="middle">
            <div id=<%= "role-mentor-#{user.id}"%>><%= render "role_btn", user: user %></div>
          </td>
          <td class="middle">
            <div id=<%= "mentors-#{user.id}"%>><%= render "groupings/mentors", user: user %></div>
          </td>
          <td class="middle">
            <div id=<%= "members-#{user.id}"%>><%= render "groupings/members", user: user %></div>
          </td>
          <td class="middle"><%= l(user.entered_at, format: :year) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @users %>

<% if @users.size.zero? %>
  <h4 class="blank-danger"><%= t("views.blank") %></h4>
<% end %>

app/views/users/mentor.html.erb
<% provide(:title, @user.name) %>
<%= render "profile_format", user: @user %>
<%= render "my_nav", user: @user %>
<%= render "member_profile", user: @user, issues: @issues, group_member: @group_member %>
<%= render "issues/search", q: @q, show_collapse: nil %>

<% issue_count = 0 %>
<% @issues&.each do |issue| %>
  <% if issue.accessible?(@user) %>
    <% issue_count += 1 %>
    <%= render "issues/issue", issue: issue %>
  <% end %>
<% end %>

<% if issue_count.zero? %>
  <h4 class="blank-danger"><%= t("views.blank") %></h4>
<% end %>

app/views/users/role_change.js.erb
$("#role-mentor-<%= @user.id %>").html("<%= j(render 'users/role_btn', {user: @user}) %>");
$("#members-<%= @user.id %>").html("<%= j(render 'groupings/members', {user: @user}) %>");

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= render "profile_format", user: @user %>
<%= render "my_nav", user: @user %>

<% issue_count = 0 %>
<% @issues&.each do |issue| %>
  <% issue_count += 1 %>
  <%= render "issues/issue", issue: issue %>
<% end %>

<% if issue_count.zero? %>
  <h4 class="blank-danger"><%= t("views.blank") %></h4>
<% end %>

app/views/users/stocked.html.erb
<% provide(:title, @user.name) %>
<%= render "profile_format", user: @user %>
<%= render "my_nav", user: @user %>
<%= render "issues/search", q: @q, show_collapse: "show" %>

<% issue_count = 0 %>
<% @issues&.each do |issue| %>
  <% if issue.accessible?(@user) %>
    <% issue_count += 1 %>
    <%= render "issues/issue", issue: issue %>
  <% end %>
<% end %>

<% if issue_count.zero? %>
  <h4 class="blank-danger"><%= t("views.blank") %></h4>
<% end %>