config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    # omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions"
    # unlocks: "users/unlocks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    resources :users, only: %i[index show] do
      member do
        get :stocked
        get :mentor
        get :edit_avatar
      end
      resources :notifications, only: %i[index update] do
        collection do
          patch :read_all
          delete :destroy_all
        end
      end
      resources :chat_rooms, only: %i[index show create] do
        collection do
          get :user_index
        end
      end
    end
  end

  resources :users_csv, only: %i[create index]

  resources :issues do
    resources :favorites, only: %i[create destroy]
    resources :stocks, only: %i[create destroy]
    resources :comments, only: %i[create edit update destroy]
  end
  resources :groupings, only: %i[create destroy]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_footer.html.erb
<div class="menu-container">
  <% if user_signed_in? %>
    <div class="nav-item <%= activate_css(:issues, :index)%>">
      <%= link_to(issues_path, class: "nav-link icon-container") do %>
        <span class="material-icons">find_in_page</span>
        <span class="icon-explanation"><%= Issue.model_name.human %></span>
      <% end %>
    </div>
    <div class="nav-item <%= activate_css(:issues, :new)%>">
      <%= link_to(new_issue_path, class: "nav-link icon-container") do %>
        <span class="material-icons">add_box</span>
        <span class="icon-explanation"><%= t("views.issues.new.title") %></span>
      <% end %>
    </div>
    <div class="nav-item <%= activate_css(:notifications, :index)%>">
      <%= link_to(user_notifications_path(current_user), class: "nav-link icon-container") do %>
        <% if (unread = current_user.notifications.unreads.presence) %>
          <div class="notification-container">
            <span class="material-icons text-warning">notifications_active</span>
            <small class="text-warning"><%= "#{unread.size}" %></small>
          </div>
        <% else %>
          <div class="notification-container">
            <span class="material-icons">notifications_none</span><small>0</small>
          </div>
        <% end %>
        <span class="icon-explanation"><%= Notification.model_name.human %></span>
      <% end %>
    </div>
    <div class="nav-item <%= activate_css(:users, :show)%>">
      <%= link_to user_path(current_user), class:"nav-link icon-container" do %>
        <%= image_tag prepare_avatar(current_user), class: "avatar25" %>
        <span class="icon-explanation"><%= t("views.users.show.title") %></span>
      <% end %>
    </div>
  <% else %>
    <div class="company">&copy; 2022 fumta</div>
  <% end %>
</div>
<div class="pc-view">
  <div class="company">&copy; 2022 fumta</div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to t("views.home.index.title"), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse header-menu" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% if current_user&.admin? %>
          <li class="nav-item">
            <%= link_to t("admin.actions.dashboard.title"), rails_admin_path, class:"nav-link" %>
          </li>
        <% end %>
        <% if current_user.mentor? %>
          <li class="nav-item <%= activate_css(:users, :index)%>">
            <%= link_to t("views.users.index.title"), users_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item pc-view <%= activate_css(:issues, :index)%>">
          <%= link_to t("views.issues.index.title"), issues_path, class: "nav-link" %>
        </li>
        <li class="nav-item pc-view <%= activate_css(:issues, :new)%>">
          <%= link_to t("views.issues.new.title"), new_issue_path, class: "nav-link" %>
        </li>
        <li class="nav-item pc-view <%= activate_css(:notifications, :index)%>">
          <%= link_to(user_notifications_path(current_user), class: "nav-link") do %>
            <% if (unread = current_user.notifications.unreads.presence) %>
              <span class="material-icons text-warning">notifications_active</span>
              <small class="text-warning"><%= "#{unread.size}" %></small>
            <% else %>
              <span class="material-icons">notifications_none</span><small>0</small>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item <%= activate_css(:chat_rooms, :index)%>">
          <%= link_to user_chat_rooms_path(current_user), class:"nav-link" do %>
            <% if all_unread_messages_count == 0 %>
              <span class="material-icons">chat</span>
            <% else %>
              <span class="material-icons text-warning">mark_unread_chat_alt</span>
            <% end %>
              <small><%= t("views.chat_rooms.index.draft") %></small>
          <% end %>
        </li>
        <li class="nav-item pc-view <%= activate_css(:users, :show)%>">
          <%= link_to user_path(current_user), class:"nav-link" do %>
            <%= image_tag prepare_avatar(current_user), class: "avatar25" %>
            <%= content_tag(:span, current_user.name) %>
          <% end %>
        </li>
        <li class="nav-item <%= activate_css(:sessions, :destroy)%>">
          <%= link_to t("devise.sessions.new.sign_out"), destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item <%= activate_css(:sessions, :guest_sign_in) %>">
          <%= link_to t("devise.sessions.new.guest_admin_sign_in"), users_guest_sign_in_path(admin: true), method: :post, class: "nav-link" %>
        </li>
        <li class="nav-item <%= activate_css(:sessions, :guest_sign_in) %>">
          <%= link_to t("devise.sessions.new.guest_sign_in"), users_guest_sign_in_path, method: :post, class: "nav-link" %>
        </li>
        <li class="nav-item <%= activate_css(:sessions, :new) %>">
          <%= link_to t("devise.sessions.new.sign_in"), new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= activate_css(:registrations, :new) %>">
          <%= link_to t("devise.registrations.new.sign_up"), new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>